library(dplyr)
glimpse(iris)
glimpse(mtcars)
str(iris)
view(iris)
mtcars['mpg']
mtcars%>%dplyr::select(vs,mpg,wt)
mtcars%>%group_by(cyl)%>% summarize(avgwt = mean(wt), meanhp = mean(hp)) %>% arrange(desc(meanhp), avgwt)
mtcars %>% filter(mpg>23|wt<2)
install.packages("gsheet")
library(gsheet)
area1 = "https://docs.google.com/spreadsheets/d/1qLHa5qFTyWacta8F-IGo6J3Zpf-BVR9OrlqONuJDqYc/edit#gid=2023826519"
df2 = as.data.frame(gsheet::gsheet2tb1(area1))
str(df2)
head(df2)
df3 = read.csv('salesslr.csv')
head(df3)
cov(df3$X,df3$Y)
cor(df3$X,df3$Y)
cor.test(df3$X,df3$Y)
plot(df3)
plot(df3$X,df3$Y,xlab = 'Area in sqft',ylab = 'Sales Amount', type = 'p', main = 'Plot of Area vs Sales')
fit1=lm(formula = Y~X, df3)
fit1
summary(fit1)
(Y=0.9645 + 1.6699*4)
fitted(fit1)
new1 = data.frame(X=c(1.5,2,3,4,5))
new1
predict(fit1, newdata = new1)
summary(fit1)
data(women)
cor(women$height,women$weight)
df4 = read.csv('salesmlr.csv')
update.packages()
y